@startuml
skinparam monochrome reverse
left to right direction
actor user

cloud "OIDC Proivder" as IP

frame notificationsPod {
    node notifications
    component "airbag" as airbag
}

airbag <--> IP
user <--> airbag
airbag <--> notifications 
@enduml