@startuml
skinparam monochrome reverse
left to right direction
actor user

frame notificationsPod {
    node notifications
    component "airbag (Envoy)" as envoyA
}

node users
node messages

user <--> airbag
envoyA <--> messages 
@enduml