@startuml
skinparam monochrome reverse

frame notificationsPod {
    node notifications
    component "sidecar" as dqd
}

cloud {
    queue "notifications queue" as queue
}


dqd <-up- queue
dqd -right-> notifications 
@enduml