@startuml
'autoinclude
left to right direction

frame "Notifications Pod" {
    node notifications
    component "proxy (Envoy)" as envoyA
}

frame "Users Pod" as UsersPod {
    node users
}

frame "Messagess Pod" as MessagesPod {
    node messages
}

notifications <--> envoyA 
envoyA <--> users:"retry"
envoyA <--> messages:"retry"
@enduml