@startuml
skinparam monochrome reverse
left to right direction
skinparam frame {
    backgroundColor Yellow
}
skinparam cloud {
    backgroundColor Yellow
}

skinparam component{
    backgroundColor Orange
}

frame "Notifications Pod" {
    node notifications
    component "proxy (Envoy)" as envoyA
}

frame "Users Pod" as UsersPod {
    node users
}

frame "Messagess Pod" as MessagesPod {
    node messages
}

notifications <--> envoyA 
envoyA <--> users:"retry"
envoyA <--> messages:"retry"
@enduml