kind: Service
apiVersion: v1
metadata:
  namespace: demo-v1
  name: notifications
spec:
  selector:
    app: notifications
    version: "1"
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: demo-v1
  name: demo-v1-ingress-notifications
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: notifications.demo-v1
    http:
      paths:
        - backend:
            serviceName: notifications
            servicePort: 80