kind: Service
apiVersion: v1
metadata:
  namespace: demo-v1
  name: notifications
spec:
  selector:
    app: notifications
    version: "2"
  ports:
    - name: http
      port: 80
      targetPort: 3001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notifications
  namespace: demo-v1
spec:
  hosts:
  - notifications.localtest.me
  gateways:
  - gateway.default.svc.cluster.local
  http:
  - appendHeaders:
     x-envoy-max-retries: "10"
     x-envoy-retry-on: connect-failure
     x-envoy-upstream-rq-timeout-ms: "0"
    route:
    - destination:
        host: notifications.demo-v1.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: notifications-dest-rule
spec:
  host: notifications.demo-v1.svc.cluster.local
  trafficPolicy: # Apply to all ports
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms