apiVersion: v1
kind: Namespace
metadata:
  name: demo-v1
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-v1
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: users
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  namespace: demo-v1
  name: users
spec:
  selector:
    app: users
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-v1
  name: messages
spec:
  selector:
    matchLabels:
      app: messages
  replicas: 1
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
      - name: messages
        image: messages
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  namespace: demo-v1
  name: messages
spec:
  selector:
    app: messages
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: demo-v1
  name: demo-v1-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: users.demo-v1
    http:
      paths:
        - backend:
            serviceName: users
            servicePort: 80
  rules:
  - host: messages.demo-v1
    http:
      paths:
        - backend:
            serviceName: messages
            servicePort: 80