apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notifications-messages
  namespace: demo-v1
spec:
  hosts:
  - messages
  http:
  - match:
    - sourceLabels:
        app: notifications
    retries:
      attempts: 4
      perTryTimeout: 2s
    route:
    - destination:
        host: messages
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notifications-users
  namespace: demo-v1
spec:
  hosts:
  - users
  http:
  - match:
    - sourceLabels:
        app: notifications
    retries:
      attempts: 4
      perTryTimeout: 1s
    route:
    - destination:
        host: users
---
