apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notifications-messages
spec:
  hosts:
  - messages
  http:
  - match:
    - sourceLabels:
        app: notifcations
    retries:
      attempts: 3
      perTryTimeout: 2s
    route:
    - destination:
        host: messages
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notifications-users
spec:
  hosts:
  - users
  http:
  - match:
    - sourceLabels:
        app: notifcations
    retries:
      attempts: 3
      perTryTimeout: 2s
    route:
    - destination:
        host: users
---
