apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: users
    workspace: ./support/users
  - imageName: messages
    workspace: ./support/messages
deploy:
  kubectl:
    manifests:
    - ./support/support.yaml