apiVersion: v1
kind: Namespace
metadata:
  name: demo-v1
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-v1
  name: graphite
spec:
  selector:
    matchLabels:
      app: graphite
  replicas: 1
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
      - name: graphite
        image:  graphiteapp/graphite-statsd
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: carbon
          containerPort: 2003
        - name: statsd
          containerPort: 8125
---
kind: Service
apiVersion: v1
metadata:
  namespace: demo-v1
  name: graphite
spec:
  selector:
    app: graphite
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: statsd
      protocol: UDP
      port: 8125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v0.12-debian-logzio
        env:
          - name: LOGZIO_TOKEN
            value: "***REMOVED***"
          - name: LOGZIO_LOGTYPE
            value: "kubernetes"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-dqd
spec:
  hosts:
  - testdqd.queue.core.windows.net
  ports:
  - number: 443
    name: https-port
    protocol: https

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - "grafana.localtest.me"
  gateways:
  - gateway
  http:
  - appendHeaders:
     x-envoy-max-retries: "10"
     x-envoy-retry-on: connect-failure
     x-envoy-upstream-rq-timeout-ms: "0"
    route:
      - destination:
          host: grafana.istio-system.svc.cluster.local
          port:
            number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicegraph
spec:
  hosts:
  - "servicegraph.localtest.me"
  gateways:
  - gateway
  http:
  - appendHeaders:
     x-envoy-max-retries: "10"
     x-envoy-retry-on: connect-failure
     x-envoy-upstream-rq-timeout-ms: "0"
    route:
      - destination:
          host: servicegraph.istio-system.svc.cluster.local
          port:
            number: 8088
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
spec:
  hosts:
  - "kiali.localtest.me"
  gateways:
  - gateway
  http:
  - appendHeaders:
     x-envoy-max-retries: "10"
     x-envoy-retry-on: connect-failure
     x-envoy-upstream-rq-timeout-ms: "0"
    route:
      - destination:
          host: kiali.istio-system.svc.cluster.local
          port:
            number: 20001
  