apiVersion: v1
kind: Namespace
metadata:
  name: demo-v1
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-v1
  name: graphite
spec:
  selector:
    matchLabels:
      app: graphite
  replicas: 1
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
      - name: graphite
        image:  graphiteapp/graphite-statsd
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: carbon
          containerPort: 2003
        - name: statsd
          containerPort: 8125
---
kind: Service
apiVersion: v1
metadata:
  namespace: demo-v1
  name: graphite
spec:
  selector:
    app: graphite
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: statsd
      protocol: UDP
      port: 8125
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: istio-system
  name: metrics-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
    - host: grafana.infra
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 3000
    - host: prom.infra
      http:
        paths:
          - backend:
              serviceName: prometheus
              servicePort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: demo-v1
  name: graphite-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
    - host: graphite.infra
      http:
        paths:
          - backend:
              serviceName: graphite
              servicePort: 80


  