---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-v1
  name: notificationsv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
      version: "2"
  template:
    metadata:
      labels:
        app: notifications
        version: "2"
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: notificationsv2
        image: notificationsv2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      # Airbag starts here!
      - name: "airbag"
        image: "soluto/airbag:0.0.3"
        ports:
          - containerPort: 3001
        env:
          - name: AUTHORITY
            value: http://oidc
          - name: ISSUER
            value: http://oidc.demo-v1
          - name: AUDIENCE
            value: http://oidc.demo-v1/resources
          - name: BACKEND_SERVICE_PORT
            value: "3000"
          - name: UNAUTHENTICATED_ROUTES
            value: isalive
          - name: ASPNETCORE_URLS
            value: http://+:3001
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: BACKEND_HOST_NAME
            value: localhost
        # Airbag ends here

        # DQD starts here
      - name: "dqd"
        image: "yshay/dqd"
        env:
          - name: STORAGE_ACCOUNT
            value: testdqd
          - name: QUEUE_NAME
            value: test
          - name: SAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: dqd
                key: sas
          - name: ERROR_SAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: dqd
                key: sas
          - name: ENDPOINT
            value: http://localhost:3000/api/notifications
        # DQD ends here